# -*- coding: utf-8 -*-
"""Kolmogorov-SmirnovTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0JTXDFrp8_eDGt5CPyTp3P57vyMiXHF

**Example 1: One Sample Kolmogorov-Smirnov Test**

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kstest.html
"""

from numpy.random import seed
from numpy.random import poisson

#set seed (e.g. make this example reproducible)
seed(0)

#generate dataset of 100 values that follow a Poisson distribution with mean=5
data = poisson(5, 100)

from scipy import stats
from scipy.stats import kstest

#perform Kolmogorov-Smirnov test
kstest(data, 'norm')

stat, p_value = kstest(data, 'norm')

if p_value < 0.05:
    print("Reject the null hypothesis. Significant differences exist between the sample mean and the population mean.")
else:
    print("Fail to reject the null hypothesis. No significant differences exist between the sample mean and the population mean.")

"""**Example 2: Two Sample Kolmogorov-Smirnov Test**

Performs the two-sample Kolmogorov-Smirnov test for goodness of fit.

This test compares the underlying continuous distributions F(x) and G(x) of two independent samples. See Notes for a description of the available null and alternative hypotheses.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html
"""

from numpy.random import seed
from numpy.random import randn
from numpy.random import lognormal

#set seed (e.g. make this example reproducible)
seed(0)

#generate two datasets
data1 = randn(100)
data2 = lognormal(3, 1, 100)

from scipy.stats import ks_2samp

#perform Kolmogorov-Smirnov test
ks_2samp(data1, data2)

stat_2, p_value_2 = ks_2samp(data1, data2)

if p_value_2 < 0.05:
    print("Reject the null hypothesis. Significant differences exist between the sample mean and the population mean.")
else:
    print("Fail to reject the null hypothesis. No significant differences exist between the sample mean and the population mean.")