# -*- coding: utf-8 -*-
"""pvalue_plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gib1PPmlkLuC0mX3-wT58zFHDFBwX1aa
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Define test statistic distribution under H0 (standard normal)
x = np.linspace(-4, 4, 1000)
pdf = norm.pdf(x, 0, 1)

# Observed value of the test statistic
t_obs = 2.0

# Compute p-value (right-tail test)
p_value = 1 - norm.cdf(t_obs)

# Plot
plt.figure(figsize=(8,5))
plt.plot(x, pdf, color='navy', lw=2, label=r'$f(t|H_0)$')
plt.fill_between(x, 0, pdf, where=(x >= t_obs), color='red', alpha=0.4,
                 label=fr'p-value = {p_value:.3f}')
plt.axvline(t_obs, color='red', linestyle='--', lw=2, label=r'$t_{obs}$')

# Annotations
plt.title("Quantifying Agreement with $H_0$ — p-value Visualization", fontsize=13)
plt.xlabel("Test Statistic  $t$")
plt.ylabel(r"Probability Density  $f(t|H_0)$")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()