# -*- coding: utf-8 -*-
"""WaldWolfowitz-RunTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ct-nFf9z1swwqkXaLCNarPz_kLuN55h
"""

# Example of the Run Test (Wald–Wolfowitz Runs Test)

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

def runs_test(data):
    """
    Perform Wald–Wolfowitz Runs Test for randomness.
    Converts numeric data to a binary sequence around the median.
    """
    data = np.asarray(data)
    median = np.median(data)
    signs = np.where(data >= median, 1, 0)

    # Count runs
    runs = 1
    for i in range(1, len(signs)):
        if signs[i] != signs[i-1]:
            runs += 1

    n1 = np.sum(signs == 1)
    n2 = np.sum(signs == 0)

    # Expected runs and variance
    mean_runs = (2*n1*n2)/(n1+n2) + 1
    var_runs = (2*n1*n2*(2*n1*n2 - n1 - n2)) / (((n1+n2)**2)*(n1+n2-1))
    z = (runs - mean_runs) / np.sqrt(var_runs)
    p_value = 2 * (1 - norm.cdf(abs(z)))

    return {"runs": runs, "mean": mean_runs, "z": z, "p": p_value}

# Example 1: Random sequence
np.random.seed(42)
data_random = np.random.randn(40)
result_random = runs_test(data_random)

# Example 2: Non-random (increasing trend)
data_nonrandom = np.linspace(1, 10, 40)
result_nonrandom = runs_test(data_nonrandom)

print("Random sequence:")
for k,v in result_random.items():
    print(f"{k:8}: {v:.4f}")

print("\nNon-random sequence:")
for k,v in result_nonrandom.items():
    print(f"{k:8}: {v:.4f}")